language: c
sudo: true
dist: trusty

os:
  - linux

compiler:
  - gcc

install:
  - sudo apt-get --yes install snapd
  - sudo snap install --edge --devmode books

before_script:
  - autoreconf -vfi

script:
  - ./configure books_CFLAGS="-I/snap/books/current/include" books_LIBS="/snap/books/current/lib/libbooks.a" || { cat config.log; false; }
  - make
  - make check
    || { cat test/test-suite.log; false; }
  - make distcheck DISTCHECK_CONFIGURE_FLAGS='books_CFLAGS="-I/snap/books/current/include" books_LIBS="/snap/books/current/lib/libbooks.a"'
    || { cat sex-*/_build/test/test-suite.log; false; }

notifications:
  email:
    - devel@fresse.org
